name: Bloop CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: graalvm@
      - run: |
          sbt "bloopInstall" "install"
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          ./coursier launch ch.epfl.scala:bloopgun-core_2.12:1.3.4 -- test frontend
        shell: bash
