name: Bloop CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: graalvm@
      - run: |
          bitsadmin /transfer downloadCoursierCli https://git.io/coursier-cli "%cd%\coursier"
          bitsadmin /transfer downloadCoursierBat https://git.io/coursier-bat "%cd%\coursier.bat"
          C:\Users\runneradmin\bin\sbt "bloopInstall" "install"
          coursier launch ch.epfl.scala:bloopgun-core_2.12:1.3.4 -- test frontend