name: Bloop CI
on:
  push:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: graalvm@
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: |
          curl -Lo coursier https://git.io/coursier-cli && chmod +x coursier && ./coursier --help
          sbt "jsBridge06/publishLocal" "jsBridge10/publishLocal" "frontend/testOnly bloop.CompileSpec bloop.bsp.TcpBspCompileSpec bloop.RunSpec"
        shell: bash
